### ISSUE TITLE
ValueError: Maximum BFS search size exceeded.

### ISSUE THREAD

**Issue by Y11190003** [tongzhugroup/reacnetgenerator#1567] opened 2022-04-28 19:11 UTC
Hello, zeng
My name is Changwei Liu. Thank you for your contribution to the analysis of the ReaxFF simulation. When I analyze the  bonds.connect file including bond sequences produced by catalytic systems containing metal clusters, the following error occurs:
'''
Traceback (most recent call last):
  File "/public1/home/scg3280/.conda/envs/0428_env/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/public1/home/scg3280/.conda/envs/0428_env/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "reacnetgenerator/_path.py", line 217, in reacnetgenerator._path._CollectSMILESPaths._calmoleculeSMILESname
  File "reacnetgenerator/_path.py", line 129, in reacnetgenerator._path._CollectPaths.convertSMILES
**ValueError: Maximum BFS search size exceeded.
This is likely due to a highly symmetric fused ring system.**
'''
How to solve this error?
Thank you very much.

**Comment by njzjz** [comment] 2022-04-28 20:31
This error is raised by rdkit [here](https://github.com/rdkit/rdkit/blob/ca75365c34b0db1f4c65cc31cf489e0d8171575c/Code/GraphMol/FindRings.cpp#L671-L673), when the BFS search size is larger than 200000.
Is your molecule very large?

There is also a fallback method that does not generate SMILES. You need to use the Python interface, and set the argument `SMILES` to false. 
See https://github.com/tongzhugroup/reacnetgenerator/blob/acbe5286218a6adb23b34361e722dbe7ecb5ef6a/reacnetgenerator/reacnetgen.py#L133 for details.

**Comment by Y11190003** [comment] 2022-04-29 03:33
Dear,
Thank you for your reply! My system does not contain macromolecules, but has a metal cluster containing 400 atoms, could it be due to the complex coordination bonds of the metal cluster causing the larger BFS search size? Okay, I will try the python interface next. Thanks!
Good day!
Changwei

**Comment by njzjz** [comment] 2022-08-10 20:46
I am going to resolve your issue by skipping the SMILES conversation. Could you provide a case for reproduction?

**Comment by ShangZhe-1999** [comment] 2022-10-10 02:23
Hello! I met the same problem when using ReacNetgenerator and I tried the way metioned above https://github.com/tongzhugroup/reacnetgenerator/issues/1567#issuecomment-1112628039, but it doesn't work. The system contains 20 molecules and 700 atoms. 
How to solve it?Look forward to your reply!

**Comment by njzjz** [comment] 2022-10-13 02:37
> Hello! I met the same problem when using ReacNetgenerator and I tried the way metioned above https://github.com/tongzhugroup/reacnetgenerator/issues/1567#issuecomment-1112628039, but it doesn't work. The system contains 20 molecules and 700 atoms. 
> 
> How to solve it?Look forward to your reply!

@ShangZhe-1999 can you provide an example?

**Comment by njzjz** [comment] 2022-10-16 05:44
Fixed by #1730. A fallback name will be provided.

**Closed** 2022-10-16 05:43 UTC

**Comment by YOUNG-JAME** [comment] 2023-10-31 02:33
> This error is raised by rdkit [here](https://github.com/rdkit/rdkit/blob/ca75365c34b0db1f4c65cc31cf489e0d8171575c/Code/GraphMol/FindRings.cpp#L671-L673), when the BFS search size is larger than 200000. Is your molecule very large?
> 
> There is also a fallback method that does not generate SMILES. You need to use the Python interface, and set the argument `SMILES` to false. See
> 
> https://github.com/tongzhugroup/reacnetgenerator/blob/acbe5286218a6adb23b34361e722dbe7ecb5ef6a/reacnetgenerator/reacnetgen.py#L133
> 
> for details.
Encounter of Maximum BFS Search Size Exceeded Error during SMILES Processing
I've come across the same issue while processing SMILES strings using RDKit. Here's the snippet of code I have been using:
m = Chem.MolFromSmiles(smiles)
if m is None:
    m = Chem.MolFromSmiles(smiles, sanitize=False)
    m.UpdatePropertyCache(strict=False)
    Chem.SanitizeMol(m, Chem.SANITIZE_SYMMRINGS | Chem.SANITIZE_SETCONJUGATION | Chem.SANITIZE_SETHYBRIDIZATION)
The error occurs as follows:
in get_vocabulary
    randomized_smi = randomize_smiles(smi)
in randomize_smiles
    Chem.SanitizeMol(m, Chem.SANITIZE_SYMMRINGS | Chem.SANITIZE_SETCONJUGATION | Chem.SANITIZE_SETHYBRIDIZATION)
ValueError: Maximum BFS search size exceeded.
This is likely due to a highly symmetric fused ring system.
I tried to follow the suggestions by modifying the reacnetgenerator/reacnetgenerator/reacnetgen.py file as mentioned, but I was unable to locate this file. Additionally, some molecules are very large, but I am not sure the BFS search size is larger than 200000.
I would appreciate any advice or solutions to this error, especially when dealing with highly symmetric fused ring systems. Many thanks for considering my request.
